/*
Total number of projects started in each country
*/

SELECT COU.COUNTRYNAME, COUNT(PRO.ProjectID) AS NumberOfProjects
FROM PROJECT_T PRO, COUNTRY_T COU, CATEGORY_T CAT, CALENDAR_T CAL
WHERE PRO.CATEGORYID = CAT.CATEGORYID
    AND PRO.COUNTRYCODE = COU.COUNTRYCODE
    AND PRO.DEADLINE = CAL.DATES
GROUP BY COU.COUNTRYNAME
ORDER BY COUNT(PRO.ProjectID) DESC;


/*
Number of projects started in each country, 
broken down to final project results (successful, failed, canceled, etc)
*/

SELECT COU.COUNTRYNAME, PRO.PROJECTSTATE, 
    COUNT(PRO.ProjectID) AS NumberOfProjects, 
    ROUND(AVG(PLEDGEDAMOUNT), 1) AS AVERAGEAMOUNTPLEDGED
FROM PROJECT_T PRO, COUNTRY_T COU, CATEGORY_T CAT, CALENDAR_T CAL
WHERE PRO.CATEGORYID = CAT.CATEGORYID
    AND PRO.COUNTRYCODE = COU.COUNTRYCODE
    AND PRO.DEADLINE = CAL.DATES
GROUP BY COU.COUNTRYNAME, PRO.PROJECTSTATE
ORDER BY ROUND(AVG(PLEDGEDAMOUNT), 1) DESC;


/*
Number of projects and average $ pledged started in each month (regardless of the year), 
broken down to final project results (successful, failed, canceled, etc)
*/

SELECT CAL.MONTH, 
    PRO.PROJECTSTATE, 
    COUNT(PRO.ProjectID) AS NumberOfProjects, 
    ROUND(AVG(PLEDGEDAMOUNT), 1) AS AVERAGEAMOUNTPLEDGED
FROM PROJECT_T PRO, COUNTRY_T COU, CATEGORY_T CAT, CALENDAR_T CAL
WHERE PRO.CATEGORYID = CAT.CATEGORYID
    AND PRO.COUNTRYCODE = COU.COUNTRYCODE
    AND PRO.DEADLINE = CAL.DATES
GROUP BY CAL.MONTH, PRO.PROJECTSTATE
ORDER BY ROUND(AVG(PLEDGEDAMOUNT), 1) DESC;